### ISSUE TITLE
it wont work

### ISSUE THREAD

**Issue by colb21** [HackerHansen/1v1.YEET-v1#1]
i tried everything and i wont work is it patched

**Comment by HackerHansen** [comment]
No, I just tried it and it works fine. Make sure you followed the instructions and used firefox

**Comment by colb21** [comment]
do you have discord i want to share my screen

**Comment by HackerHansen** [comment]
sorry but I don't have the time to provide direct support for this. Make sure you select the right process, otherwise it won't work.
