### ISSUE TITLE
God Mode doesn't work.

### ISSUE THREAD

**Issue by Outcalled** [HackerHansen/1v1.YEET-v1#15]
Hello, I am doing everything correctly. "Infinite Ammo, Rapid Fire etc." works fine but not God Mode. Would really nice if it would be fixed!

**Comment by Outcalled** [comment]
Also could you make this work on any other browser and not Firefox? It's the worst browser possible for gaming, Atleast Brave & Microsoft Edge are fine. Personally I use Microsoft Edge. If you can make it compatible with that it would be nice.

**Comment by HackerHansen** [comment]
Firefox is the easiest to use cheat engine on since it doesn't launch a bunch of processes. 

I'll go see if I can fix god mode sometime today 

Edit: Spelling

**Comment by HackerHansen** [comment]
Also, I ever make a v2 I'll add brave support

**Comment by HackerHansen** [comment]
Ok so I just got on my PC and checked, god mode still works for me. Idk why it's not working for you, maybe redownload it and try again?

**Comment by Outcalled** [comment]
Weird, I'll try later. But I will be thankful if you added Brave support :)
