### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SomeRandomGithub-User** [HackerHansen/1v1.YEET-v1#18]
![image](https://user-images.githubusercontent.com/73361689/106822781-be878700-664d-11eb-9cf9-1bef4a572345.png)
How do I fix this

**Comment by HackerHansen** [comment]
Are you using Cheat Engine 7.2?

**Comment by SomeRandomGithub-User** [comment]
> Are you using Cheat Engine 7.2?

Yes I am

**Comment by HackerHansen** [comment]
Idk why it's having this issue 

Try redownloading the trainer maybe?

**Comment by SomeRandomGithub-User** [comment]
The issue is still there but I am gonna close the thread
