### ISSUE TITLE
some modes like rapid fire dont work im doing it right

### ISSUE THREAD

**Issue by Vortex-Twisty** [HackerHansen/1v1.YEET-v1#19]

**Comment by HackerHansen** [comment]
"This hack will no longer be updated since v2 has been released."

A lot of the things are broken. I'll update the status in the README

**Comment by Vortex-Twisty** [comment]
pls update it

**Comment by HackerHansen** [comment]
I said: 

> "This hack will no longer be updated since v2 has been released." 

Please read my comment before replying. If you want somethig that works better and gets updated then use v2
