### ISSUE TITLE
Hacks arent working

### ISSUE THREAD

**Issue by TRSSeize** [HackerHansen/1v1.YEET-v1#3]
My hacks arent working and i did everything im mad

**Comment by HackerHansen** [comment]
They work fine for me, I just checked. Make sure you're on the latest version of Firefox. Also make sure speed works, if it doesn't work at all you're doing it wrong.

**Comment by TRSSeize** [comment]
oh ok i was on the old firefox instead of the new bing one do i get that instead

**Comment by TRSSeize** [comment]
danm im using the new version and its still not working

**Comment by HackerHansen** [comment]
Are you using Windows 10 64-bit? It's only been tested on there

**Comment by TRSSeize** [comment]
ya

**Comment by HackerHansen** [comment]
Hmm, idk what's the problem here. Did you test if speedhack works? Enter a number in the speed box and press enter. If it doesn't work then you're attached to the wrong process.

**Comment by TRSSeize** [comment]
i did that
it didnt work
but i chose the progress with the most ram and put the pid in

**Comment by TRSSeize** [comment]
im sad

**Comment by HackerHansen** [comment]
Speedhack will always work, so you're attached to the wrong process. 
At this point after clicking "attach process" just YOLO and try every firefox process to see if it works.

**Comment by TRSSeize** [comment]
k
