### ISSUE TITLE
Taking Over 5 Minutes to Attach

### ISSUE THREAD

**Issue by MantisGalaxy** [HackerHansen/1v1.YEET-v1#7]
I followed all the steps and clicked attach process, it froze for a bit but now it's taking a while. Am I doing something wrong?

**Comment by MantisGalaxy** [comment]
EDIT
I re-ran it and it said "Process Attached. Starting Initial Scan, this might take a while" but after that it just freezes then crashes if I try checking it

**Comment by MantisGalaxy** [comment]
EDIT 2
I got bored of waiting and when I closed FireFox it finished scanning

**Comment by HackerHansen** [comment]
When you close firefox it doesnt finish, it just displays that message since it can't scan anymore. 

The program states that the scan may take a while and will look like it froze, but it hasn't taken 5 minutes for me. Maybe just leave it there for a while I guess
